# Generated by Django 5.2.7 on 2025-10-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateField()),
                ('firewall', models.CharField(max_length=100)),
            ],
        ),
    ]
