# Generated by Django 5.2.8 on 2025-11-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motocicletas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Motocicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('propietario', models.CharField(max_length=100)),
                ('cilindrage', models.PositiveIntegerField()),
                ('fecha_fabricacion', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Software',
        ),
    ]
