# Generated by Django 5.2.7 on 2025-10-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motocicleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
                ('propietario', models.CharField(max_length=100)),
                ('cilindraje', models.PositiveIntegerField()),
                ('fecha_fabricacion', models.PositiveIntegerField()),
            ],
        ),
    ]
